### ISSUE TITLE
How to whitelist libraries that install a shutdown-hook?

### ISSUE THREAD

**Issue by Wallenstein61** [ls1intum/Ares#83]
**Is your feature request related to a problem? Please describe.**

We want to test solutions that are using the java-awt library.
This library installs a shutdown hook, although this is not used in context of the exercise.

Currently the sandbox raises an security exception. I have not found a way, to whitelist such a feature.

I could imagine that there are also other libraries that uses features like a shutdown hook.

**Describe the solution you'd like**

I would like to add an exception of this exception.

**Describe alternatives you've considered**

Just not use the sandbox :-(

**Comment by MaisiKoleni** [comment]
What could work depending on the library is using `@AddTrustedPackage` to place the packages on the same level as `java.**`.

Due to the way AJTS handles Threads, it might not be enough. I have not yet tried to use shutdown hooks and will take a look at that.

There are at the moment and in foreseeable future some test setups where AJTS cannot be used at all.
